import Script from "next/script";
import "../assets/css/bootstrap.min.css";
import "../assets/icon/bootstrap-icons.min.css";
import "./globals.css";
import "primereact/resources/themes/lara-dark-cyan/theme.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <body>
        {children}
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></Script>
      </body>
    </html>
  );
}
